refine_original <- read.csv("~/Dropbox/SpringBrd Intro DS/IDS Proj 1/refine_original.csv")
refine_clean <- refine_original
refine_clean$company <- tolower(refine_clean$company)
refine_clean$company <- str_replace(refine_clean$company, " ", "")
refine_clean$company <- gsub("\\b[ph|f]\\S*\\b", "philips", refine_clean$company)
refine_clean$company <- gsub("\\b[u]\\S*\\b", "unilever", refine_clean$company)
refine_clean$company <- gsub("\\b[v]\\S*\\b", "van houten", refine_clean$company)
refine_clean$company <- gsub("\\b[a]\\S*\\b", "akzo", refine_clean$company)
refine_clean <- separate(refine_clean, 2, c("product_code", "product_number"), "-", replace = TRUE)
refine_clean$product_category <- refine_clean$product_code
refine_clean$product_category <- gsub("\\b[p]\\b", "Smartphone", refine_clean$product_category)
refine_clean$product_category <- gsub("\\b[v]\\b", "TV", refine_clean$product_category)
refine_clean$product_category <- gsub("\\b[x]\\b", "Laptop", refine_clean$product_category)
refine_clean$product_category <- gsub("\\b[q]\\b", "Tablet", refine_clean$product_category)
refine_clean$full_address <- paste(refine_clean$address,",",refine_clean$city, ",", refine_clean$country)
refine_clean$company_philips <- as.integer(refine_clean$company == "philips")
refine_clean$company_akzo <- as.integer(refine_clean$company == "akzo")
refine_clean$company_vanhouten <- as.integer(refine_clean$company == "van houten")
refine_clean$company_unilever <- as.integer(refine_clean$company == "unilever")
refine_clean$product_smartphone <- as.integer(refine_clean$product_category == "Smartphone")
refine_clean$product_tv <- as.integer(refine_clean$product_category == "TV")
refine_clean$product_laptop <- as.integer(refine_clean$product_category == "Laptop")
refine_clean$product_tablet <- as.integer(refine_clean$product_category == "Tablet")
View(refine_clean)
write.csv(refine_clean, "refine_clean.csv")
